"""empty message

Revision ID: 33aa22d50558
Revises: 7b4ebf6469ff
Create Date: 2021-08-18 12:26:18.090134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33aa22d50558'
down_revision = '7b4ebf6469ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin_attachment', sa.Column('filename', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulletin_attachment', 'filename')
    # ### end Alembic commands ###
