"""empty message

Revision ID: 34deb28c8471
Revises: 8b0d45b32e46
Create Date: 2021-08-10 13:58:43.063881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34deb28c8471'
down_revision = '8b0d45b32e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('content', sa.String(length=40000), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('cover_pic', sa.String(length=400), nullable=True),
    sa.Column('important', sa.Boolean(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approve_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['bulletin_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletin_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletin_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bulletin_viewer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=True),
    sa.Column('viewer_id', sa.Integer(), nullable=True),
    sa.Column('view_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin.id'], ),
    sa.ForeignKeyConstraint(['viewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bulletin_viewer')
    op.drop_table('bulletin_comment')
    op.drop_table('bulletin_attachment')
    op.drop_table('bulletin')
    op.drop_table('bulletin_topic')
    # ### end Alembic commands ###
