"""empty message

Revision ID: 8003f08684ef
Revises: ba0cec3df3ae
Create Date: 2021-08-15 13:17:59.812307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8003f08684ef'
down_revision = 'ba0cec3df3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_joined', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date_joined')
    # ### end Alembic commands ###
