"""empty message

Revision ID: a572eb5a8fca
Revises: 1ae3652757e2
Create Date: 2021-07-04 16:18:28.724290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a572eb5a8fca'
down_revision = '1ae3652757e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_subscription', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'push_subscription', ['id'])
    op.create_foreign_key(None, 'push_subscription', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'push_subscription', type_='foreignkey')
    op.drop_constraint(None, 'push_subscription', type_='unique')
    op.drop_column('push_subscription', 'user_id')
    # ### end Alembic commands ###
