"""empty message

Revision ID: ba0cec3df3ae
Revises: a5f7a3bb3c14
Create Date: 2021-08-15 10:52:27.774575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0cec3df3ae'
down_revision = 'a5f7a3bb3c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_topic_logs',
    sa.Column('bulletin_topic_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['bulletin_topic_id'], ['bulletin_topic.id'], )
    )
    op.create_table('cme_course_topic_logs',
    sa.Column('cme_course_topic_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_topic_id'], ['cme_course_topic.id'], )
    )
    op.create_table('designation_logs',
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designation.id'], )
    )
    op.create_table('role_logs',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    op.create_table('cme_course_logs',
    sa.Column('cme_course_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_id'], ['cme_course.id'], )
    )
    op.create_table('user_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('activation_logs',
    sa.Column('user_activation_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['user_activation_id'], ['user_activation.id'], )
    )
    op.create_table('bulletin_logs',
    sa.Column('bulletin_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin.id'], )
    )
    op.create_table('cme_course_content_logs',
    sa.Column('cme_course_content_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_content_id'], ['cme_course_content.id'], )
    )
    op.create_table('cme_course_post_test_logs',
    sa.Column('cme_course_post_test_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_post_test_id'], ['cme_course_post_test.id'], )
    )
    op.create_table('cme_course_pre_test_logs',
    sa.Column('cme_course_pre_test_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_pre_test_id'], ['cme_course_pre_test.id'], )
    )
    op.create_table('cme_course_question_logs',
    sa.Column('cme_course_question_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_question_id'], ['cme_course_question.id'], )
    )
    op.create_table('cme_course_review_logs',
    sa.Column('cme_course_review_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_review_id'], ['cme_course_review.id'], )
    )
    op.create_table('cme_course_user_question_logs',
    sa.Column('cme_course_user_question_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_user_question_id'], ['cme_course_user_question.id'], )
    )
    op.create_table('bulletin_attachment_logs',
    sa.Column('bulletin_attachment_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['bulletin_attachment_id'], ['bulletin_attachment.id'], )
    )
    op.create_table('bulletin_comment_logs',
    sa.Column('bulletin_comment_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['bulletin_comment_id'], ['bulletin_comment.id'], )
    )
    op.create_table('cme_content_slide_logs',
    sa.Column('cme_content_slides_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_content_slides_id'], ['cme_content_slides.id'], )
    )
    op.create_table('cme_content_video_logs',
    sa.Column('cme_content_video_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_content_video_id'], ['cme_content_video.id'], )
    )
    op.create_table('cme_course_question_choices_logs',
    sa.Column('cme_course_question_choices_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_question_choices_id'], ['cme_course_question_choices.id'], )
    )
    op.create_table('cme_course_post_test_response_logs',
    sa.Column('cme_course_post_test_response_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_post_test_response_id'], ['cme_course_post_test_response.id'], )
    )
    op.create_table('cme_course_pre_test_response_logs',
    sa.Column('cme_course_pre_test_response_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['cme_course_pre_test_response_id'], ['cme_course_pre_test_response.id'], )
    )
    op.drop_constraint('bulletin_log_id_fkey', 'bulletin', type_='foreignkey')
    op.drop_column('bulletin', 'log_id')
    op.drop_constraint('bulletin_attachment_log_id_fkey', 'bulletin_attachment', type_='foreignkey')
    op.drop_column('bulletin_attachment', 'log_id')
    op.drop_constraint('bulletin_comment_log_id_fkey', 'bulletin_comment', type_='foreignkey')
    op.drop_column('bulletin_comment', 'log_id')
    op.drop_constraint('bulletin_topic_log_id_fkey', 'bulletin_topic', type_='foreignkey')
    op.drop_column('bulletin_topic', 'log_id')
    op.drop_constraint('cme_content_slides_log_id_fkey', 'cme_content_slides', type_='foreignkey')
    op.drop_column('cme_content_slides', 'log_id')
    op.drop_constraint('cme_content_video_log_id_fkey', 'cme_content_video', type_='foreignkey')
    op.drop_column('cme_content_video', 'log_id')
    op.drop_constraint('cme_course_log_id_fkey', 'cme_course', type_='foreignkey')
    op.drop_column('cme_course', 'log_id')
    op.drop_constraint('cme_course_content_log_id_fkey', 'cme_course_content', type_='foreignkey')
    op.drop_column('cme_course_content', 'log_id')
    op.drop_constraint('cme_course_question_log_id_fkey', 'cme_course_question', type_='foreignkey')
    op.drop_column('cme_course_question', 'log_id')
    op.drop_constraint('cme_course_question_choices_log_id_fkey', 'cme_course_question_choices', type_='foreignkey')
    op.drop_column('cme_course_question_choices', 'log_id')
    op.drop_constraint('cme_course_topic_log_id_fkey', 'cme_course_topic', type_='foreignkey')
    op.drop_column('cme_course_topic', 'log_id')
    op.drop_constraint('designation_log_id_fkey', 'designation', type_='foreignkey')
    op.drop_column('designation', 'log_id')
    op.drop_constraint('push_subscription_log_id_fkey', 'push_subscription', type_='foreignkey')
    op.drop_column('push_subscription', 'log_id')
    op.drop_constraint('role_log_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'log_id')
    op.drop_constraint('user_log_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'log_id')
    op.drop_constraint('user_activation_log_id_fkey', 'user_activation', type_='foreignkey')
    op.drop_column('user_activation', 'log_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_activation', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_activation_log_id_fkey', 'user_activation', 'activity_log', ['log_id'], ['id'])
    op.add_column('user', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_log_id_fkey', 'user', 'activity_log', ['log_id'], ['id'])
    op.add_column('role', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('role_log_id_fkey', 'role', 'activity_log', ['log_id'], ['id'])
    op.add_column('push_subscription', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('push_subscription_log_id_fkey', 'push_subscription', 'activity_log', ['log_id'], ['id'])
    op.add_column('designation', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('designation_log_id_fkey', 'designation', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_course_topic', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_course_topic_log_id_fkey', 'cme_course_topic', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_course_question_choices', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_course_question_choices_log_id_fkey', 'cme_course_question_choices', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_course_question', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_course_question_log_id_fkey', 'cme_course_question', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_course_content', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_course_content_log_id_fkey', 'cme_course_content', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_course', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_course_log_id_fkey', 'cme_course', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_content_video', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_content_video_log_id_fkey', 'cme_content_video', 'activity_log', ['log_id'], ['id'])
    op.add_column('cme_content_slides', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cme_content_slides_log_id_fkey', 'cme_content_slides', 'activity_log', ['log_id'], ['id'])
    op.add_column('bulletin_topic', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bulletin_topic_log_id_fkey', 'bulletin_topic', 'activity_log', ['log_id'], ['id'])
    op.add_column('bulletin_comment', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bulletin_comment_log_id_fkey', 'bulletin_comment', 'activity_log', ['log_id'], ['id'])
    op.add_column('bulletin_attachment', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bulletin_attachment_log_id_fkey', 'bulletin_attachment', 'activity_log', ['log_id'], ['id'])
    op.add_column('bulletin', sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bulletin_log_id_fkey', 'bulletin', 'activity_log', ['log_id'], ['id'])
    op.drop_table('cme_course_pre_test_response_logs')
    op.drop_table('cme_course_post_test_response_logs')
    op.drop_table('cme_course_question_choices_logs')
    op.drop_table('cme_content_video_logs')
    op.drop_table('cme_content_slide_logs')
    op.drop_table('bulletin_comment_logs')
    op.drop_table('bulletin_attachment_logs')
    op.drop_table('cme_course_user_question_logs')
    op.drop_table('cme_course_review_logs')
    op.drop_table('cme_course_question_logs')
    op.drop_table('cme_course_pre_test_logs')
    op.drop_table('cme_course_post_test_logs')
    op.drop_table('cme_course_content_logs')
    op.drop_table('bulletin_logs')
    op.drop_table('activation_logs')
    op.drop_table('user_logs')
    op.drop_table('cme_course_logs')
    op.drop_table('role_logs')
    op.drop_table('designation_logs')
    op.drop_table('cme_course_topic_logs')
    op.drop_table('bulletin_topic_logs')
    # ### end Alembic commands ###
