"""empty message

Revision ID: e8537c0b4882
Revises: 8003f08684ef
Create Date: 2021-08-15 14:41:03.525812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8537c0b4882'
down_revision = '8003f08684ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('two_factor_authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('two_fa_code', sa.String(length=6), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_authentication_two_fa_code'), 'two_factor_authentication', ['two_fa_code'], unique=False)
    op.create_table('department_logs',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('activity_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_log_id'], ['activity_log.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], )
    )
    op.create_table('user_departments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_departments')
    op.drop_table('department_logs')
    op.drop_index(op.f('ix_two_factor_authentication_two_fa_code'), table_name='two_factor_authentication')
    op.drop_table('two_factor_authentication')
    op.drop_table('department')
    # ### end Alembic commands ###
