"""empty message

Revision ID: f9868519c839
Revises: 07a70eb8234f
Create Date: 2021-06-13 16:12:00.012580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9868519c839'
down_revision = '07a70eb8234f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cme_course_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('cover_page', sa.String(length=256), nullable=True),
    sa.Column('cme_points', sa.Integer(), nullable=True),
    sa.Column('cme_serial_no', sa.String(length=100), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('presentation_date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['cme_course_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cme_course_cover_page'), 'cme_course', ['cover_page'], unique=False)
    op.create_table('cme_course_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course_creators',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cme_course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cme_course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('cme_course_post_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course_pre_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('answer_explanation', sa.String(length=1000), nullable=True),
    sa.Column('image_file', sa.String(length=256), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cme_course_question_image_file'), 'cme_course_question', ['image_file'], unique=False)
    op.create_table('cme_course_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_submitted', sa.Date(), nullable=True),
    sa.Column('q1', sa.Integer(), nullable=True),
    sa.Column('q2', sa.Integer(), nullable=True),
    sa.Column('q3', sa.Integer(), nullable=True),
    sa.Column('q4', sa.Integer(), nullable=True),
    sa.Column('q5', sa.Integer(), nullable=True),
    sa.Column('q6', sa.Integer(), nullable=True),
    sa.Column('q7', sa.Integer(), nullable=True),
    sa.Column('q8', sa.Integer(), nullable=True),
    sa.Column('q9', sa.Integer(), nullable=True),
    sa.Column('q10', sa.Integer(), nullable=True),
    sa.Column('q11', sa.Integer(), nullable=True),
    sa.Column('q12', sa.Integer(), nullable=True),
    sa.Column('q13', sa.Integer(), nullable=True),
    sa.Column('q14', sa.Integer(), nullable=True),
    sa.Column('q15', sa.Integer(), nullable=True),
    sa.Column('q16', sa.Integer(), nullable=True),
    sa.Column('q17', sa.Integer(), nullable=True),
    sa.Column('q18', sa.Integer(), nullable=True),
    sa.Column('q19', sa.Integer(), nullable=True),
    sa.Column('q20', sa.Integer(), nullable=True),
    sa.Column('q21', sa.String(length=5000), nullable=True),
    sa.Column('q22', sa.String(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course_user_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=1000), nullable=True),
    sa.Column('answer', sa.String(length=5000), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('date_answered', sa.Date(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('questioned_by_id', sa.Integer(), nullable=True),
    sa.Column('answered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answered_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['questioned_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_content_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.String(length=256), nullable=True),
    sa.Column('sound_file', sa.String(length=256), nullable=True),
    sa.Column('slide_text', sa.String(length=4000), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_content_id'], ['cme_course_content.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cme_content_slides_image_file'), 'cme_content_slides', ['image_file'], unique=False)
    op.create_index(op.f('ix_cme_content_slides_sound_file'), 'cme_content_slides', ['sound_file'], unique=False)
    op.create_table('cme_content_views',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cme_course_content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cme_course_content_id'], ['cme_course_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('cme_course_question_choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['cme_course_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course_post_test_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posttest_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_choice_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['posttest_id'], ['cme_course_post_test.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['cme_course_question.id'], ),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['cme_course_question_choices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cme_course_pre_test_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pretest_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('selected_choice_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.ForeignKeyConstraint(['pretest_id'], ['cme_course_pre_test.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['cme_course_question.id'], ),
    sa.ForeignKeyConstraint(['selected_choice_id'], ['cme_course_question_choices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cme_course_pre_test_response')
    op.drop_table('cme_course_post_test_response')
    op.drop_table('cme_course_question_choices')
    op.drop_table('cme_content_views')
    op.drop_index(op.f('ix_cme_content_slides_sound_file'), table_name='cme_content_slides')
    op.drop_index(op.f('ix_cme_content_slides_image_file'), table_name='cme_content_slides')
    op.drop_table('cme_content_slides')
    op.drop_table('cme_course_user_question')
    op.drop_table('cme_course_review')
    op.drop_index(op.f('ix_cme_course_question_image_file'), table_name='cme_course_question')
    op.drop_table('cme_course_question')
    op.drop_table('cme_course_pre_test')
    op.drop_table('cme_course_post_test')
    op.drop_table('cme_course_creators')
    op.drop_table('cme_course_content')
    op.drop_index(op.f('ix_cme_course_cover_page'), table_name='cme_course')
    op.drop_table('cme_course')
    op.drop_table('cme_course_topic')
    # ### end Alembic commands ###
