"""empty message

Revision ID: 42ce72fc37b2
Revises: 34deb28c8471
Create Date: 2021-08-10 14:47:19.392777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ce72fc37b2'
down_revision = '34deb28c8471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('nursing_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nursing_course',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=5000), autoincrement=False, nullable=True),
    sa.Column('submitted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], name='nursing_course_approved_by_id_fkey'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], name='nursing_course_submitted_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nursing_course_pkey')
    )
    op.drop_table('user_roles')
    op.drop_table('role')
    # ### end Alembic commands ###
