"""empty message

Revision ID: 7b4ebf6469ff
Revises: d2b35c5bbd24
Create Date: 2021-08-18 12:17:16.865310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4ebf6469ff'
down_revision = 'd2b35c5bbd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin_attachment', sa.Column('filetype', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bulletin_attachment', 'filetype')
    # ### end Alembic commands ###
