"""empty message

Revision ID: 8b0d45b32e46
Revises: a572eb5a8fca
Create Date: 2021-08-07 15:29:36.905311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b0d45b32e46'
down_revision = 'a572eb5a8fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cme_content_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_file', sa.String(length=256), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('course_content_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_content_id'], ['cme_course_content.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['cme_course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cme_content_video_video_file'), 'cme_content_video', ['video_file'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cme_content_video_video_file'), table_name='cme_content_video')
    op.drop_table('cme_content_video')
    # ### end Alembic commands ###
