"""empty message

Revision ID: d2b35c5bbd24
Revises: e8537c0b4882
Create Date: 2021-08-18 10:54:43.490369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b35c5bbd24'
down_revision = 'e8537c0b4882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_departments',
    sa.Column('bulletin_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], )
    )
    op.create_table('bulletin_designations',
    sa.Column('bulletin_id', sa.Integer(), nullable=True),
    sa.Column('designation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designation.id'], )
    )
    op.add_column('bulletin_attachment', sa.Column('filepath', sa.String(length=400), nullable=True))
    op.drop_column('bulletin_attachment', 'file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin_attachment', sa.Column('file', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.drop_column('bulletin_attachment', 'filepath')
    op.drop_table('bulletin_designations')
    op.drop_table('bulletin_departments')
    # ### end Alembic commands ###
