"""empty message

Revision ID: ef56d19b2ba3
Revises: 6dd8ce1b7a42
Create Date: 2021-08-11 15:19:20.569924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef56d19b2ba3'
down_revision = '6dd8ce1b7a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bulletin', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('bulletin_topic', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('cme_content_slides', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('cme_content_video', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('cme_course', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('cme_course_content', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('cme_course_topic', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('designation', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('role', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'deleted')
    op.drop_column('designation', 'deleted')
    op.drop_column('cme_course_topic', 'deleted')
    op.drop_column('cme_course_content', 'deleted')
    op.drop_column('cme_course', 'deleted')
    op.drop_column('cme_content_video', 'deleted')
    op.drop_column('cme_content_slides', 'deleted')
    op.drop_column('bulletin_topic', 'deleted')
    op.drop_column('bulletin', 'deleted')
    # ### end Alembic commands ###
